aliases:
  - &android
    components:
      - build-tools-23.0.1
      - android-23
      - extra-android-m2repository
      - extra-android-support - &android-cache
    directories:
      - ~/.cache/yarn
      - ~/.gradle/caches/modules-2
      - ~/.gradle/wrappers
  
  - &ios-cache
    directories:
      - ~/.rncache
      - ~/Library/Caches/Yarn
      - ~/Library/Caches/CocoaPods

  - &init-new-project
    |
      nvm install node
      yarn global add react-native-cli
      react-native init App --version="0.54.2"
      cd App
      yarn add react-native-baidumap-sdk

jobs:
  include:
    - stage: "build test for new project"
      language: objective-c
      osx_image: xcode9.2
      cache: *ios-cache
      script:
        - brew install yarn
        - *init-new-project
        - cd ios
        - |
          cat << EOF > Podfile
            platform :ios, '11.0'
            target 'App' do
              pod 'React', path: '../node_modules/react-native', :subspecs => [
                'DevSupport',
                'RCTNetwork',
              ]
              pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
              pod 'react-native-baidumap-sdk', path: '../node_modules/react-native-baidumap-sdk/lib/ios'
            end
          EOF
        - pod install
        - xcodebuild -workspace App.xcworkspace -scheme App -sdk iphonesimulator -quiet

stages:
  - "build test for new project"
